language: python
python:
- '3.4'
branches:
  except:
    - master
    - ci
env:
  matrix:
    - FORMAT=hst TF=M1
    - FORMAT=hst TF=M2
    - FORMAT=hst TF=M3
    - FORMAT=hst TF=M4
    - FORMAT=hst TF=M5
    - FORMAT=hst TF=M6
    - FORMAT=hst TF=M10
    - FORMAT=hst TF=M12
    - FORMAT=hst TF=M15
    - FORMAT=hst TF=M20
    - FORMAT=hst TF=M30
    - FORMAT=hst TF=H1
    - FORMAT=hst TF=H2
    - FORMAT=hst TF=H3
    - FORMAT=hst TF=H4
    - FORMAT=hst TF=H6
    - FORMAT=hst TF=H8
    - FORMAT=hst TF=H12
    - FORMAT=hst TF=D1
    - FORMAT=hst TF=W1
    - FORMAT=hst TF=MN1
    - FORMAT=fxt TF=M1
    - FORMAT=fxt TF=M5
    - FORMAT=fxt TF=M15
    - FORMAT=fxt TF=M30
    - FORMAT=fxt TF=H1
    - FORMAT=fxt TF=H4
    - FORMAT=fxt TF=D1
    - FORMAT=fxt TF=W1
    - FORMAT=fxt TF=MN1
addons:
  apt:
    packages:
    - realpath
    - pv
notifications:
  email: false
before_install:
- set -e
install: 
before_script:
- curl -o Makefile https://raw.githubusercontent.com/FX-Data/FX-Data-Test/master/Makefile
script:
- make $FORMAT
after_success: 
after_failure:
- sudo apt-get -qy install tree && tree -d -L 6
- env
after_script:
- pwd
deploy:
  provider: releases
  api_key:
    secure: "FstTY2P2Agsu0azDnZ2cFEEQ2VilngMs0BwdIM+rI9d7x2oOB9wTJQczuq2eHahoxu5cHEgt7fj2YqThZZp/Mco3nOCBukEiwdbNYbb784Uks2IQuMAYa6qQxFdMiJS3htS356tN/WkpX8LICd35YH/w36P9ziS9atdQkNEa0uq2EFzwjX3YenDEWJgP2EklnzyHt8i49WJV4qYBROeYE6ItmcM6s3npo+AemHKZ6j0Sc1NJogk/G8F9voLk+ol9T+OA3yLf3bEGp1ZqlMODu5cxvJ7mW3GUQUFs7y+wJQMV8U2lAGg4yhDBETlfpUunK2zehcVpPZ85daGENBGg5exNjaj6dQyNbdB8R7FNllNeFeO6Zfw3vj3dcFjZXM2tKsS+FAOKPGQnUDI6WFydYZ335HQHpfDWRj7BjNYsXc/7KGxsuTIQV/Z+8JJG7AdFuBDmc8oRB8g4vBmyu2A4Ve1qKEBenAC2VCv0rN8HG6Lc9gQacURTmCXgIvOWQD45USlgSpfbV04iN7JeuWgpN9c+vA+euYxQPMx+xciWGI03Qr+gft52eBzkDwP7gSuAFQ/yQTY0tbYjO/veWfMqicx6DZzVl9JRXEhyxly9GCexEo2+o3RhvIjYXXnHxopaTOuY6nKKXOvQFxsX/VclwjAY3P/H9SEDLGozQLUGKIc="
  file:
    - "*.hst.gz"
    - "*.fxt.gz"
  file_glob: true
  skip_cleanup: true
  overwrite: true
  on:
    repo: FX-Data/FX-Data-CHFJPY-DS
    tags: true
after_deploy:
- make clean
